### ISSUE TITLE
Steel and Concrete Uniaxial Materials

### ISSUE THREAD

**Issue by subedinaresh** [denavit/OpenSees-Packages#4]
Hi, 

Thank you for making the packages publicly available. I think it would be great to have the _sakinoSunConcrete0_4 and _shenSteel0_1 available in the main OpenSees executable. 

Is it possible to add these material models to the main OpenSees repository so that novice users of OpenSees can also use the aforementioned materials.   

Thank you.

**Comment by denavit** [comment]
Thank you for your interest in these material models. 

There are a couple of reasons that I don't think these these models are ready for general use. The sakinoSunConcrete04 is simply based on a model already in OpenSees but with a different backbone curve, however, I have not kept it up to date. The shenSteel01 model is a plasticity type model, but is step size dependent and currently implemented. I would want to implemented a fix to that (e.g., sub-stepping) before making it widely available.
